"""update otp

Revision ID: c056a3844407
Revises: ec8ae1bf9367
Create Date: 2024-06-09 15:01:21.198003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c056a3844407'
down_revision: Union[str, None] = 'ec8ae1bf9367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('count_attempts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp', 'count_attempts')
    # ### end Alembic commands ###
